# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core', '~> 4.13.0'

target 'staRtrn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for staRtrn

  target 'staRtrn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'staRtrnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
